<h1> Numpy Basics </h1>
    
__Author__ : `Hossam.__Asaad__()`

<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li><a href="#S1">Importing and Version</a></li>
        <li><a href="#S2">Creating Numpy Array From python list</a></li>
        <li><a href="#S3">Creating list from Scratch</a></li>
        <li><a href="#S4">
            Basics Operations of NumPy Arrays
            <ul>
                <li><a>NumPy Array Attributes</a></li>
                <li><a>Array Indexing: Accessing Single Elements</a></li>
                <li><a>Reshaping of Arrays</a></li>
                <li><a>Array Concatenation and Splitting</a></li>
            </ul>
        </a></li>
        <li><a href="#S5">Computation on NumPy Arrays: Universal Functions</a></li>
        <li><a href="#S6">Aggregations: Min, Max, and Everything in Between</a></li>
        <li><a href="#S7">Comparison Operators</a></li>
        <li><a href="#S8">Fancey Indexing</a></li>
        <li><a href="#S9">Array Sorting</a></li>
    </ul>
<p>
</div>

<hr>

<h2 id='S1'> Importing Numpy Library as 'np' To use it. </h2>

##### np.__version__  : return numpy version

In [1]:
import numpy as np
np.__version__

'1.16.5'



<h2 id="S1"> Creating Numpy Array From python list </h2>

### Syntax : 
np.array(list, dtype='arrayType')
dtype = int32 by default

In [2]:
l = [1, 2, 3]                                   # Creating a python list

iArray = np.array(l)                            # Integer Numpy Array 
fArray = np.array(l, dtype='float32')           # Float Numpy Array

print('Integer Array : ', iArray)
print('Float Array :', fArray)

Integer Array :  [1 2 3]
Float Array : [1. 2. 3.]


#### Two-dimensional array using python list of lists

In [3]:
l = [[1,2,3]
    ,[7,8,9]
    ,[4,5,6]]

_2dArray = np.array(l)
_2dArray

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

<h2 id="S3"> Creating list from Scratch</h2>

### np.zeros(n, dtype='X')
return a numpy array :
- `length =  n`
- `all elements = 0`
- `type = X`

In [4]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### np.ones(n, dtype='X')
return a numpy array :
- `length =  n`
- `all elements = 1`
- `type = X`

In [5]:
np.ones(5, dtype = float)

array([1., 1., 1., 1., 1.])

### np.full(n, X)
return a numpy array :
- `length =  n`
- `all elements = X`
- `type = X type`

### 2D-array
`To Create 2D-Array, just replace length with a tuple = (r, c)`

In [6]:
np.full((2,3), 4.5)

array([[4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5]])

### np.arange(S, E, step)
Create an array filled with a linear sequence,,
- `Starting at S`
- `ending at E`
- `stepping by step`

In [7]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### np.linspace(S, E, n)
`Create an array of n values evenly spaced between S and E`

In [8]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### np.random.random(X)
Create a `size = X` array of uniformly distributed random values between 0 and 1



In [9]:
np.random.random((2,3))

array([[0.22955128, 0.71435631, 0.34774667],
       [0.18346623, 0.42245227, 0.21221437]])

### np.random.normal(M, std, X)
Create a `size = X` array of normally distributed random values with `mean = M` and `standard deviation = std`

In [10]:
np.random.normal(2,.5, 5)

array([2.09045454, 1.97443205, 1.68925866, 2.03757634, 2.3015896 ])

### np.random.randint(s, e, X))
Create a 'size = X' array of random integers in the interval `[s, e]`

In [11]:
np.random.randint(0,10, (2,3))

array([[6, 6, 1],
       [9, 8, 1]])

### np.eye(N)
Create a `N*N` identity matrix

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<h2 id="S4">Basics Operations of NumPy Arrays<h2>

### NumPy Array Attributes
Determining the size, shape, memory consumption, and data types of arrays
- `ndim ` : return the number of dimensions
- `shape` : return the size of each dimension
- `size ` : return the total size of the array
- `dtype` : return the data type of the array

In [13]:
a = np.random.randint(0,10, size=(2,3,5))

print('Number of Dimensions    :',a.ndim)
print('Size of each Dimensions :',a.shape)
print('Total Array size        :',a.size)
print('Array Data type         :',a.dtype)

Number of Dimensions    : 3
Size of each Dimensions : (2, 3, 5)
Total Array size        : 30
Array Data type         : int32


### Array Indexing: Accessing Single Elements
Getting and setting the value of individual array elements

- In a one-dimensional array, you can access the ith value (counting from
zero) by specifying the desired index in square brackets, just as with Python lists
- To index from the end of the array, you can use negative indices,
- In a multidimensional array, you access items using a comma-separated tuple of
indices:

In [14]:
a = np.array([4,3,2,7,5])                   # 1D-Array
b = np.array([[1,4,5],[2,3,4]])               # 2D-Array

print(a[3])             # Accessing element of 1-D Array
print(a[-1])            # Access Last element in the array
print(b[1,1])           # accessing element in 2d-Array at (1,1)

7
5
3


### Array Slicing: Accessing Subarrays
Getting and setting smaller subarrays within a larger array

- The NumPy slicing syntax follows that of the standard Python list
- to access a slice of an array x, `x[start:stop:step]`

In [15]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([[1,2,3]
    ,[4,5,6]
    ,[7,8,9]])

In [16]:
a[2:]    # elements after index 2

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
a[:2]   # first two elements

array([1, 2])

In [16]:
a[2:4]  # From inedx 2 to 4 

array([3, 4])

In [17]:
a[::2]

array([1, 3, 5, 7, 9])

In [18]:
a[1::2]

array([2, 4, 6, 8])

In [19]:
b[:1, :2]       # one row and two columns

array([[1, 2]])

In [20]:
b[:2, ::]

array([[1, 2, 3],
       [4, 5, 6]])

### Subarrays as no-copy
This is one area in which NumPy
array slicing differs from Python list slicing: in lists, slices will be copies
if we modify this subarray, we’ll see that the original array is changed!
- This default behavior is actually quite useful: it means that when we work with large
datasets, we can access and process pieces of these datasets without the need to copy
the underlying data buffer

### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly
copy the data within an array or a subarray. This can be most easily done with the
copy() method

In [21]:
a = np.array([[1,2,3]
    ,[4,5,6]
    ,[7,8,9]])

sub1 = a[:2,:2]
sub2 = a[:2,:2].copy()
print(sub1)
print(sub2)

[[1 2]
 [4 5]]
[[1 2]
 [4 5]]


In [22]:
sub2[0, 0] = 99
sub2

array([[99,  2],
       [ 4,  5]])

In [23]:
a   # Notice that the change in sub-array using copy() doesn't change the main array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
sub1[0, 0] = 99
sub1

array([[99,  2],
       [ 4,  5]])

In [25]:
a   # Notice that the change in sub-array change the main array

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

### Reshaping of Arrays
The size of the initial array must match the size of the
reshaped array.
- The most flexible way of
doing this is with the `reshape()` method. For example, if you want to put the numbers
1 through 9 in a 3×3 grid

In [26]:
grid = np.arange(1, 10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array Concatenation and Splitting
#### Concatenation of arrays
combine multiple arrays into one using
- `np.concatanate([l1,..])` : concatenate two arrays or more
- `np.vstack,([l1,..])` : vertically stack the arrays
- `np.hstack([l1,..])`  : horizontally stack the arrays

In [27]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [28]:
grid1 = [[1,2]
        ,[3,4]]
grid2 = [[5,6]
        ,[7,8]]
np.concatenate([grid1,grid2])                   # concatenate along y-axis (columns)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [29]:
np.concatenate([grid1,grid2], axis = 1)         # concatenate along x-axix (rows)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Splitting of arrays
The opposite of concatenation is splitting, split a single array into multiple arrays
which is implemented by the functions
- `np.split(array, indeciesList])` : split array into two arrays or more
- `np.vsplit,(array, indeciesList])` : vertically split the arrays
- `np.hsplit([array, indeciesList])`  : horizontally split the arrays
- indeciesList : list of indecies at which split stop

In [30]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
np.split(x,[3,5])  

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [31]:
x = np.array([[ 0, 1, 2, 3],
[ 4, 5, 6, 7],
[ 8, 9, 10, 11],
[12, 13, 14, 15]])

upper, lower = np.split(x, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [32]:
left, right = np.split(x, [2], axis = 1)
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


<h2 id='S5'> Computation on NumPy Arrays: Universal Functions </h2>

### Array arithmetic

Double-click __here__ for Functions Summary.
<!--
Operator    Equivalent ufunc            Description
- '+'        np.add             Addition         (e.g., 1 + 1 = 2)
- '-'        np.subtract        Subtraction      (e.g., 3 - 2 = 1)
- '-'        np.negative        Unary negation   (e.g., -2)
- '*'        np.multiply        Multiplication   (e.g., 2 * 3 = 6)
- '/'        np.divide          Division         (e.g., 3 / 2 = 1.5)
- '//'       np.floor_divide    Floor division   (e.g., 3 // 2 = 1)
- '**'       np.power           Exponentiation   (e.g., 2 ** 3 = 8)
- '%'        np.mod             Modulus/remainder(e.g., 9 % 4 = 1)
-->

In [33]:
x = np.array([1,-2,3,-4])
x

array([ 1, -2,  3, -4])

In [34]:
x + 5 # Addition

array([6, 3, 8, 1])

In [35]:
x - 5 # Substraction

array([-4, -7, -2, -9])

In [36]:
x * 5 # multiplication,

array([  5, -10,  15, -20])

In [37]:
x / 2 # divison

array([ 0.5, -1. ,  1.5, -2. ])

In [38]:
x // 2 # integer (floor) division

array([ 0, -1,  1, -2], dtype=int32)

In [39]:
2 * x - 1 # Make some calculations

array([ 1, -5,  5, -9])

In [40]:
np.abs(x) # absolute values

array([1, 2, 3, 4])

### Trigonometric functions
The values are computed to within machine precision, which is why values that
should be zero do not always hit exactly zero

In [41]:
theta = np.linspace(0, np.pi, 3)

print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


### Exponents and logarithms

In [42]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))
print('--------------')
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]
--------------
x = [1, 2, 3]
ln(x) = [0.         0.69314718 1.09861229]
log2(x) = [0.        1.        1.5849625]
log10(x) = [0.         0.30103    0.47712125]


### Aggregates
- calling reduce on the add ufunc returns the sum of all elements in the
array
- If we’d like to store all the intermediate results of the computation, we can instead use
accumulate

In [43]:
x = np.array([1,2,3,4])

In [44]:
np.add.reduce(x)

10

In [45]:
np.multiply.reduce(x)

24

In [46]:
np.add.accumulate(x)

array([ 1,  3,  6, 10], dtype=int32)

In [47]:
np.multiply.accumulate(x)

array([ 1,  2,  6, 24], dtype=int32)

<h2 id='S6'> Aggregations: Min, Max, and Everything in Between </h2>

### Summing the Values in an Array
computing the sum of all values in an array `np.sum(array)`
### Minimum and Maximum
To find the minimum value and maximum value of any given array `np.max(array)`, `np.min(array)

Double-click __here__ for more aggregates Functions.

<!--
Function Name       NaN-safe             Version Description
np.sum             np.nansum            Compute sum of elements
np.prod            np.nanprod           Compute product of elements
np.mean            np.nanmean           Compute median of elements
np.std             np.nanstd            Compute standard deviation
np.var             np.nanvar            Compute variance
np.min             np.nanmin            Find minimum value
np.max             np.nanmax            Find maximum value
np.argmin          np.nanargmin         Find index of minimum value
np.argmax          np.nanargmax         Find index of maximum value
np.median          np.nanmedian         Compute median of elements
np.percentile      np.nanpercentile     Compute rank-based statistics of elements
np.any             N/A                  Evaluate whether any elements are true
np.all             N/A                  Evaluate whether all elements are true
-->

In [48]:
L = np.random.random(10)
L

array([0.45368531, 0.98768009, 0.29826625, 0.60182761, 0.75050658,
       0.3774948 , 0.96804298, 0.55939135, 0.06279673, 0.80590054])

In [49]:
np.max(L)

0.9876800887520597

In [50]:
np.min(L)

0.06279673017904419

In [51]:
L.min()     # shorter syntax is to use methods of the array

0.06279673017904419

### Multidimensional aggregates

In [52]:
L = np.random.random((3,4))
L

array([[0.81525335, 0.85614634, 0.20151492, 0.31052559],
       [0.28854245, 0.18911473, 0.13928051, 0.006984  ],
       [0.1002504 , 0.02250328, 0.45385202, 0.0189649 ]])

In [53]:
L.sum()

3.4029324855528302

In [54]:
L.max()

0.8561463404587953

In [55]:
L.max(axis=0)  # Max in each column

array([0.81525335, 0.85614634, 0.45385202, 0.31052559])

In [56]:
L.min(axis=1)  # Minimum in each row

array([0.20151492, 0.006984  , 0.0189649 ])

<h2 id='S7'> Comparison Operators </h2>

NumPy also implements comparison
operators such as < (less than) and > (greater than) as element-wise ufuncs.
The result of these comparison operators is always an array with a Boolean data type
### Counting entries
To count the number of True entries in a Boolean array, `np.count_nonzero`

In [57]:
L = np.array([1, 2, 3, 4, 5])
L

array([1, 2, 3, 4, 5])

In [58]:
L > 2

array([False, False,  True,  True,  True])

In [59]:
L <= 2

array([ True,  True, False, False, False])

In [60]:
L != 3

array([ True,  True, False,  True,  True])

In [61]:
L == 1

array([ True, False, False, False, False])

In [62]:
(2 * L) == (L ** 2)

array([False,  True, False, False, False])

In [63]:
np.count_nonzero(L < 4)   # how many values less than 4?

3

In [64]:
np.any(L > 4)             # are there any values greater than 4?

True

In [65]:
np.all(L < 5)             # are all values less than 5? 

False

In [66]:
(L > 1) & (L < 4)         # values greater than 1 and less than 4

array([False,  True,  True, False, False])

In [67]:
np.sum((L > 1) & (L < 4)) # Count these values

2

In [68]:
L[L>3]                   # masking operation (select the values that returned True)

array([4, 5])

<h2 id='S8'> Fancy Indexing</h2>

Fancy indexing is like the simple indexing, but we pass
arrays of indices in place of single scalars. This allows us to very quickly access and
modify complicated subsets of an array’s values.

In [69]:
L = np.random.randint(100, size=10)
L

array([35, 42, 73, 40, 75, 52, 51, 53, 25, 59])

In [70]:
L[[3,5,7]]

array([40, 52, 53])

In [71]:
ind = np.array([[1,5]
               ,[2,4]])
L[ind]

array([[42, 52],
       [73, 75]])

<h2 id = 's9'> Sorting Arrays </h2>

- To return a sorted version of the array without modifying the input, you can use
`np.sort`
- A related function is `np.argsort`, which instead returns the indices of the sorted
elements:
- By default `np.sort` uses an `O(N log N)`

In [72]:
L = np.array([4,7,6,8,9,2])
L

array([4, 7, 6, 8, 9, 2])

In [73]:
np.sort(L)

array([2, 4, 6, 7, 8, 9])

In [74]:
np.argsort(L)

array([5, 0, 2, 1, 3, 4], dtype=int64)

In [75]:
L = [[4,2,8]
    ,[3,1,7]
    ,[7,5,9]]
L

[[4, 2, 8], [3, 1, 7], [7, 5, 9]]

In [76]:
np.sort(L)   # sorting each rows

array([[2, 4, 8],
       [1, 3, 7],
       [5, 7, 9]])

In [77]:
np.sort(L, axis=0)  # sorting each columns

array([[3, 1, 7],
       [4, 2, 8],
       [7, 5, 9]])